spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.15.129:3306/gulimail_pms?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

alibaba:
  cloud:
    access-key: LTAI5t8WuNmMMwu82zNyfz8o
    secret-key: KCrfTsuCtrmimImGZrAp5zhWjvQZdc
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com