spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.15.129:3306/gulimail_ums?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000